name = "Fabricated Adventures 1.21"
author = "AgentK"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6abb83634d170f744fc527fbd65ee9708dfdaa2684a5a047c9cd93b60556637"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
