name = "Fabricated Adventures 1.21"
author = "AgentK"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8a58a6f31463f62eb79f7b753a755db5bd7368e65a4840ccea0f0d6e4ec31bf"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
